### ISSUE TITLE
jquery

### ISSUE THREAD

**Issue by daimond113** [MuckyDriver/muckydriver.github.io#1]
plz stop it use [React](https://reactjs.org)

**Comment by lukadev-0** [comment]
+1

**Comment by daimond113** [comment]
also use [material-ui](https://material-ui.com)

**Comment by lukadev-0** [comment]
Use [Next.JS](https://nextjs.org), the React framework for

# PRODUCTION

**Comment by lemurmad** [comment]
![Dog3](https://user-images.githubusercontent.com/74666933/122583625-5f04a380-d051-11eb-8eb4-70ccbf9ca812.jpg)

**Comment by lemurmad** [comment]
![Dog1](https://user-images.githubusercontent.com/74666933/122583908-a428d580-d051-11eb-8e21-8f111c29af11.jpg)
![Dog2](https://user-images.githubusercontent.com/74666933/122583918-a723c600-d051-11eb-94f7-f605a0933c23.jpg)
![Dog3](https://user-images.githubusercontent.com/74666933/122583922-a9862000-d051-11eb-8c0b-901fc63a9575.jpg)

**Comment by MarsRon** [comment]
Just use normal JavaScript smh

**Comment by lukadev-0** [comment]
no use react

**Comment by lukadev-0** [comment]
its very good

**Comment by quantix-dev** [comment]
sus

**Comment by MuckyDriver** [comment]
@daimond113 Ok my revamped website does not use JQuery
and good news for if you care
It will be using React.js very soon just getting things ready and stuff.
